# Generated by Django 5.2.8 on 2025-11-11 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="venta",
            options={},
        ),
        migrations.RemoveField(
            model_name="venta",
            name="cantidad",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="precio_unitario",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="producto",
        ),
        migrations.RemoveField(
            model_name="venta",
            name="vendedor",
        ),
        migrations.AddField(
            model_name="venta",
            name="tipo",
            field=models.CharField(
                choices=[("venta", "Venta"), ("devolucion", "Devolución")],
                default="venta",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="venta",
            name="vendido_por",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="cliente",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tienda.cliente",
            ),
        ),
        migrations.AlterField(
            model_name="venta",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name="VentaDetalle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(default=1)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tienda.producto",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="tienda.venta",
                    ),
                ),
            ],
        ),
    ]
