# Generated by Django 5.2.8 on 2025-11-13 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0002_alter_venta_options_remove_venta_cantidad_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliente_perfil",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="perfilusuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("cliente", "Cliente"),
                    ("vendedor", "Vendedor"),
                    ("gerente", "Gerente"),
                    ("administrador", "Administrador"),
                ],
                default="vendedor",
                max_length=20,
            ),
        ),
    ]
